Include /etc/httpd/modules

ServerName     LAMP.container
ServerAdmin    me@mail.de
ServerRoot     "/lib/httpd"
PidFile        "/var/run/httpd.pid"
TypesConfig    "/etc/httpd/mime.types"
ErrorLog       "|/usr/bin/logger -t httpd"
CustomLog      "|/usr/bin/logger -t httpd" "%h %l %u %t \"%r\" %>s %b"
LogLevel       warn
User           httpd
Group          httpd
Listen         443

<VirtualHost *:443>
    DocumentRoot "/var/web"
    DirectoryIndex index.html index.php

    SSLEngine on
    SSLCertificateFile /etc/httpd/cert.pem
    SSLCertificateKeyFile /etc/httpd/key.pem

    <Directory "/var/web">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>
</VirtualHost>
