ap_scan=0
eapol_version=1

network={
  key_mgmt=IEEE8021X
  eap=MD5
  identity="username"
  password="password"
  eapol_flags=0
}

#network={
#  key_mgmt=IEEE8021X
#  phase2="auth=MSCHAPV2"
#  identity="username"
#  ca_cert="/etc/wpa_root_cert.pem"
#  client_cert="/etc/wpa_client_cert.pem"
#  private_key="/etc/wpa_client_key.pem"
#  eapol_flags=0
#}
