## Here is an example for Makefiles.

syntax "makefile" "Makefile[^/]*$" "\.(make|mk)$"
comment "#"

color red "[:=]"
color magenta "\b(if|ifeq|else|endif)\b"
color blue "\$+[{(][a-zA-Z0-9_-]+[})]"
color brightblue "^[^ 	]+:"
color green "#.*$"

## Trailing whitespace.
color ,green "[[:space:]]+$"
